name: Docker Image CI

on: [push]

env:
  container: kali-${{github.sha}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t $container .

    - name: Run the Docker image
      run: docker run --name $container -id --rm $container

    - name: Verify AutoRecon is available in the container
      run: docker exec --tty $container env TERM=xterm sh -c 'autorecon -h'

    - name: Verify that Proxychains-ng is available in the container
      run: if [ "$(docker exec --tty $container env TERM=xterm sh -c 'which proxychains4' | sed 's/\r//')" = "/usr/bin/proxychains4" ]; then exit 0; else exit 1; fi;
    
    - name: Verify that MSFDB is initialized
      # Extract the "Active:" row, remove carriage returns, and remove leading whitespace
      run: |
        if [ "$(docker exec --tty $container env TERM=xterm sh -c 'msfdb status | sed -n 3p' | sed 's/\r//' \
          | sed -e 's/^[ \t]*//')" = 'Active: active (running)' ]; then exit 0; else exit 1; fi;
    
    - name: Verify that Proxychains-ng is available in the container
      run: docker exec --tty $container env TERM=xterm sh -c 'msfconsole -v'
    
    - name: Keep image size in check
      run: |
        docker pull wagoodman/dive \
        && docker run --rm -id -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive:latest \
        --tty env TERM=xterm --ci --ci-config .dive-ci $container
      env:
        CI: true
