name: Docker Image CI

on: [push]

env:
  container: kali

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t $container .

    - name: Test the Docker image
      run: docker run --name $container -id --rm $container

    - name: Verify AutoRecon is available in the container
      run: if [ $(docker exec --tty $container env TERM=xterm sh -c 'autorecon -h') = '/usr/bin/proxychains4' ]; then exit 0; else exit 1;

    - name: Verify that Proxychains-ng is working
      run: docker exec --tty $container env TERM=xterm sh -c 'which proxychains4'
    
    - name: Verify that MSFDB is initialized
      run: "docker exec --tty $container env TERM=xterm sh -c 'msfdb status | sed -n 3p' = 'Active: active (running)'"
    
    - name: Verify that Proxychains-ng is working
      run: docker exec --tty $container env TERM=xterm sh -c 'msfconsole -v'
    
    - name: Keep image size in check
      run: |
        docker pull wagoodman/dive \
        && docker run --rm -it --tty -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive:latest \
        env TERM=xterm --ci --ci-config .dive-ci $container
      env:
        CI: true
